import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, Menu, Send, X } from 'lucide-react'
import { Category, Project, projects } from './data/projects'

type Page = 'home' | 'about' | 'works' | 'skills' | 'contact' | 'project'
const nav: { label: string; page: Exclude<Page, 'project'> }[] = [{ label: 'HOME', page: 'home' }, { label: 'ABOUT', page: 'about' }, { label: 'WORKS', page: 'works' }, { label: 'SKILLS', page: 'skills' }, { label: 'CONTACT', page: 'contact' }]
const categories = ['ALL', 'PRODUCT VISUAL', 'AI CREATIVE', 'BRANDING', 'PACKAGING', 'E-COMMERCE'] as const

export default function App() {
  const [page, setPage] = useState<Page>('home'); const [selected, setSelected] = useState<Project>(projects[0]); const [menuOpen, setMenuOpen] = useState(false)
  const go = (target: Exclude<Page, 'project'>) => { setPage(target); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const openProject = (project: Project) => { setSelected(project); setPage('project'); window.scrollTo(0, 0) }
  useEffect(() => { const handler = () => document.documentElement.style.setProperty('--scroll', `${window.scrollY}px`); window.addEventListener('scroll', handler); return () => window.removeEventListener('scroll', handler) }, [])
  return <><Header page={page} go={go} open={menuOpen} setOpen={setMenuOpen} />
    <main>{page === 'home' && <Home go={go} />} {page === 'about' && <About />} {page === 'works' && <Works openProject={openProject} />} {page === 'skills' && <Skills />} {page === 'contact' && <Contact />} {page === 'project' && <ProjectDetail project={selected} openProject={openProject} back={() => go('works')} />}</main>
    <Footer go={go} /></>
}

function Header({ page, go, open, setOpen }: { page: Page; go: (p: Exclude<Page, 'project'>) => void; open: boolean; setOpen: (v: boolean) => void }) { return <header className="site-header"><button className="wordmark" onClick={() => go('home')}>YI<span>·</span>STUDIO</button><nav>{nav.map(item => <button className={page === item.page ? 'active' : ''} onClick={() => go(item.page)} key={item.page}>{item.label}</button>)}</nav><button className="menu-toggle" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>{open && <div className="mobile-nav">{nav.map(item => <button onClick={() => go(item.page)} key={item.page}>{item.label}</button>)}</div>}</header> }

function Home({ go }: { go: (p: Exclude<Page, 'project'>) => void }) { return <>
  <section className="hero"><div className="hero-image" /><div className="hero-overlay" /><div className="hero-content fade-up"><p className="eyebrow">INDEPENDENT DESIGN STUDIO · 2026</p><h1>DESIGNING<br />THE FUTURE</h1><p className="hero-sub">Product · Brand · AI Visual Design</p><p className="lede">I create modern product visuals, brand experiences and AI-powered creative content.</p><div className="actions"><button className="button light" onClick={() => go('works')}>VIEW MY WORK <ArrowUpRight /></button><button className="text-button" onClick={() => go('contact')}>CONTACT ME <ArrowRight /></button></div></div><div className="scroll-note">SCROLL TO EXPLORE <ChevronDown /></div></section>
  <section className="intro section"><p className="eyebrow">SELECTED WORK / 01—06</p><div className="intro-copy"><h2>Visual stories for<br /><i>objects with purpose.</i></h2><button className="circle-link" onClick={() => go('works')}><ArrowDownRight /></button></div></section>
  <section className="feature-work"><img src={projects[0].cover} alt="Velocity S1 electric mobility campaign" /><div className="feature-label"><p>01 / PRODUCT VISUAL</p><h3>VELOCITY S1</h3><button onClick={() => go('works')}>EXPLORE PROJECT <ArrowUpRight /></button></div></section>
  <section className="statement section"><p className="eyebrow">THE APPROACH</p><h2>Thoughtful direction.<br />Distinctive <i>outcomes.</i></h2><p>I connect strategy, visual craft and emerging creative tools to make brands and products feel desirable, clear and ready for what’s next.</p></section>
  <section className="mini-grid">{projects.slice(1, 4).map(p => <article key={p.slug} className="mini-card"><img src={p.cover} alt={p.title} /><p>{p.category}</p><h3>{p.title}</h3></article>)}</section>
</> }

function About() { const capabilities = ['PRODUCT DESIGN', 'BRAND DESIGN', 'AI VISUAL CREATION', 'E-COMMERCE DESIGN', 'PACKAGING DESIGN', 'VISUAL COMMUNICATION']; return <section className="page section about"><p className="eyebrow">01 / PROFILE</p><h1>ABOUT ME</h1><div className="about-grid"><div><p className="display-copy">I’m a visual designer creating <i>future-facing</i> identities and product stories.</p><p className="body-copy">With a focus on product, brand and digital visuals, I shape the details that make an idea feel tangible. My practice pairs rigorous visual systems with a curious, image-led approach.</p></div><div className="portrait"><img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1100&q=85" alt="Designer portrait" /></div></div><div className="principles"><article><span>01</span><h3>DESIGN DIRECTION</h3><p>Product visuals, identity systems and experience-led launch campaigns.</p></article><article><span>02</span><h3>PHILOSOPHY</h3><p>Reduce to the essential, then make every remaining choice count.</p></article><article><span>03</span><h3>WORKING STYLE</h3><p>Collaborative, precise and always informed by the bigger picture.</p></article></div><div className="capabilities"><p className="eyebrow">CAPABILITIES</p><div>{capabilities.map((x, i) => <span key={x}>{String(i + 1).padStart(2, '0')} &nbsp; {x}</span>)}</div></div></section> }

function Works({ openProject }: { openProject: (p: Project) => void }) { const [filter, setFilter] = useState<typeof categories[number]>('ALL'); const shown = useMemo(() => filter === 'ALL' ? projects : projects.filter(x => x.category === filter as Category), [filter]); return <section className="page section works"><p className="eyebrow">02 / SELECTED PROJECTS</p><h1>WORKS</h1><div className="filters">{categories.map(x => <button key={x} className={filter === x ? 'selected' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div><div className="work-grid">{shown.map((p, index) => <button className={`project-card c${index % 3}`} key={p.slug} onClick={() => openProject(p)}><img src={p.cover} alt={p.title} loading="lazy" /><span className="project-shade"><small>{p.category} · {p.year}</small><strong>{p.title}</strong><em>{p.description}</em><ArrowUpRight /></span></button>)}</div></section> }

function Skills() { const skills = [['01', 'Adobe Photoshop', 'Advanced image craft, compositing and campaign retouching.'], ['02', 'Adobe Illustrator', 'Identity systems, iconography and considered vector illustration.'], ['03', 'Figma', 'Interfaces, e-commerce systems and collaborative design direction.'], ['04', 'AI Image Generation', 'Art-directed image creation across concepts, products and worlds.'], ['05', 'Prompt Engineering', 'Repeatable visual languages built with intentional creative prompts.'], ['06', 'Brand Visual Design', 'Distinctive visual foundations designed to move with a brand.'], ['07', 'Product Advertising', 'High-impact visual stories that make product value immediate.'], ['08', 'E-Commerce Visual', 'Clear, conversion-aware content designed for every touchpoint.']]; return <section className="page section skills"><p className="eyebrow">03 / EXPERTISE</p><h1>SKILLS</h1><p className="skills-lede">A balanced toolkit for making purposeful, premium visual experiences.</p><div className="skills-grid">{skills.map(s => <article key={s[0]}><span>{s[0]}</span><ArrowUpRight /><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section> }

function Contact() { const submit = (e: FormEvent) => { e.preventDefault(); alert('Thank you — your message is on its way.') }; return <section className="page section contact"><p className="eyebrow">04 / GET IN TOUCH</p><h1>LET’S CREATE<br />SOMETHING <i>GREAT.</i></h1><div className="contact-grid"><div><p className="body-copy">Have a project, an idea, or an ambitious problem? Let’s make it feel exceptional.</p><a href="mailto:hello@yistudio.design">hello@yistudio.design <ArrowUpRight /></a><div className="socials"><a href="#contact">BEHANCE</a><a href="#contact">INSTAGRAM</a><a href="#contact">LINKEDIN</a></div></div><form onSubmit={submit}><label>Name<input required placeholder="Your name" /></label><label>Email<input type="email" required placeholder="Your email" /></label><label>Message<textarea required placeholder="Tell me about your project" rows={4} /></label><button className="button dark">SEND MESSAGE <Send /></button></form></div></section> }

function ProjectDetail({ project, openProject, back }: { project: Project; openProject: (p: Project) => void; back: () => void }) { const i = projects.findIndex(p => p.slug === project.slug); const next = projects[(i + 1) % projects.length]; const prev = projects[(i + projects.length - 1) % projects.length]; return <article className="detail"><button className="back" onClick={back}><ArrowLeft /> ALL PROJECTS</button><img className="detail-cover" src={project.cover} alt={project.title} /><section className="section detail-info"><div><p className="eyebrow">{project.category} / {project.year}</p><h1>{project.title}</h1></div><div><p className="body-copy">{project.description}</p><p className="body-copy muted">{project.concept}</p></div></section><div className="gallery">{project.gallery.slice(1).map((img, index) => <img src={img} alt={`${project.title} visual ${index + 2}`} key={img} />)}</div><div className="project-nav"><button onClick={() => openProject(prev)}><small>PREVIOUS</small><span><ArrowLeft /> {prev.title}</span></button><button onClick={() => openProject(next)}><small>NEXT PROJECT</small><span>{next.title} <ArrowRight /></span></button></div></article> }

function Footer({ go }: { go: (p: Exclude<Page, 'project'>) => void }) { return <footer><button className="wordmark" onClick={() => go('home')}>YI<span>·</span>STUDIO</button><p>© 2026 YI STUDIO. ALL RIGHTS RESERVED.</p><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>BACK TO TOP ↑</button></footer> }
